version: "3"

services:
  db:
    container_name: ecommerce_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: root1
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: ecommerce
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
