services:
  db:
    container_name: ecommerce_db
    image: mysql:latest
    restart: always
    ports:
      - 3307:3306
      - 33070:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_AUTHENTICATION_PLUGIN: mysql_native_password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
